### ISSUE TITLE
推荐在cli模式运行

### ISSUE THREAD

**Issue by sy-records** [ihewro/PullSinaimgtoTypecho#1]
😬`fpm`是阻塞的，时间长肯定超时导致失败，运行这种代码还是`cli`模式运行比较好

**Comment by ihewro** [comment]
直接命令行调用php，拿不到typecho的数据库对象db，所以没办法操作博客数据库

我也没查到的好的办法🤒

**Comment by sy-records** [comment]
```
$db = Typecho_Db::get(); //获取数据库对象
```
静态调用不应该拿不到吧😂
不用`typecho`，具体的不太清楚

**Comment by Wigiesen** [comment]
依赖Typecho_Db，如果命令行模式肯定找不到Typecho_Db的调用

**Comment by ihewro** [comment]
暂时可以修改`$GLOBALS['limit']` 为一个较小值保证不会超时，然后多次调用🤒

**Comment by Wigiesen** [comment]
神奇思路，可以有

**Comment by sy-records** [comment]
> 依赖Typecho_Db，如果命令行模式肯定找不到Typecho_Db的调用

 @Wigiesen    @ihewro 用不了吗？引入`config.inc.php`就可以啊？所以避免超时还是用`cli`模式运行最好。 

![image](https://user-images.githubusercontent.com/33931153/56808133-58a88180-6863-11e9-8cbc-60035b3b155e.png)

**Comment by Wigiesen** [comment]
@sy-records 很强势……
